import time
a=input("Enter password:")
if a!="WooderSigma145":
	print(f"incorrect password!")
	print(f"password in tg - @TaymDLC")
	exit()
else:
	print(f"Succesful! please wait...")
print("MEFIK BY WOODER")
print("1 < Number Search")
print("2 < Telegram Search")
print("3 < IP Search")
print("4 < Ddos URL")
print("5 < Spam Number")
print("6 < Spam Me")
print("7 < Database")
print(" ")
print(" Owner - @Wooder_zone ")
b = 1
x = 0
g = 0
x = int(input())
if x == 1:
	c = input("Enter Number:")
	print("please wait...")
	time.sleep(4)
	print("copied!")
	while b == 1:
		g = input()
if x == 2:
	c = input("Enter Username:")
	print("copied!")
	while b == 1:
		g = input()
if x == 3:
 c = input("Enter IP:")
 print("copied!")
 while b == 1:
  g = input() 
if x == 4:
 c = input("Enter URL:")
 print("please wait...")
 time.sleep(4)
 print("Attached!")
 time.sleep(2)
 print("1")
 time.sleep(1)
 print("2")
 time.sleep(1)
 print("3")
 time.sleep(1)
 print("4")
 time.sleep(1)
 print("5")
 print("Site Killed.")
 while b == 1:
  g = input() 
if x == 5:
 c = input("Enter Number:")
 c = input("Enter Message:")
 print("Spamim...") 
 time.sleep(10)
 print("successful!")
 while b == 1:
  g = input()
if x == 6:
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("SPAM")
 print("SPAM")
 time.sleep(0.1)
 print("Successful!")
 while b == 1:
  g = input() 
if x == 7:
 print("Numbers telegram ipbd gb gb")

 
 
 